//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace GlobonsTestASPNET.Models.BD
{
    using System;
    using System.Collections.Generic;


    public partial class Persona
    {
        public int idPersona { get; set; }
        [Required(ErrorMessage = "Ingrese un nombre")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Ingrese un apellido")]
        public string apellido { get; set; }
        [Required(ErrorMessage = "Ingrese un DNI")]
        [Range(1000000, 99999999, ErrorMessage = "Ingrese un DNI valido")]
        public int numeroDocumento { get; set; }
        [Required(ErrorMessage = "Ingrese una fecha")]
        [DataType(DataType.Date, ErrorMessage = "Invalid Date Format")]
        public System.DateTime fechaNacimiento { get; set; }
        public int direccion { get; set; }
    
        public virtual Direccion Direccion1 { get; set; }
    }


}
